#!/usr/bin/env python3
"""
Sync and optimize marketing and social preview assets generated by Stitch.
Fetches high-res renders from Stitch Google Cloud CDN and processes them for
WhatsApp previews (<300KB), Twitter cards, Apple touch icons, and PWA favicons.
"""

import os
import sys
import urllib.request
import io
from PIL import Image

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
MARKETING_DIR = os.path.join(ASSETS_DIR, "marketing")

STITCH_ASSETS = {
    "banner_16_9": {
        "url": "https://lh3.googleusercontent.com/aida/AEtjO1VPDuXk2GC8NEuYwr_yrnV1q5wuuHMDt--S4ZYaYkfXigiozVoQKEklFVGidI6cItf_-M3gzoay9M8P5JkLKTQq7-rASwwoQuHCCW8gNTzukehlPEsWEDMkN3hh16MGESzWHTtPqxkDoKH93k9m6u853IuPFotvDctNOuxiUPyZB6gRUawMeTu53ub0GT-eZ18VF177Vvx7z1lY9V7ep0bCvN7ZqKKsZ87uiXo5LjAyAQQboCHpdF_xaP0",
        "width": 1376,
        "height": 768
    },
    "social_card_1_1": {
        "url": "https://lh3.googleusercontent.com/aida/AEtjO1X1IKyuWZ9WTRKkns-kbfMxEEN5wmROseggBymuOc2Y62f77mobPBlRtRKyef6najQIkwCfJeUAuW2lctYkCBiopCLnkgxCM5mTT4Vhbt-EwglxLwfIEUzDLDdy0Qeqza5ZXFNWKvgK4bfglxSDpQ-ZUl-n-5EroVR2-A8hp-4yPYLav2_Y-3UpD2sE8jgrCTfy0P2V6HjFouR34NMl2srPiOlGznaONDE98A6eua-l1eTzA-I9g8eZLzs",
        "width": 1024,
        "height": 1024
    },
    "email_header": {
        "url": "https://lh3.googleusercontent.com/aida/AEtjO1VpNXXtNYMn3V47TChsCQ48DLb5b8fLQEH2i3jf_jrY96UNakvHWDhweHDo6W8w-8GRSD0_sM9UTXavJsRO9RDASjioHtuMU-cmwBOE98uFicB_M-dIFwAb9uN6LAZkUwFSpeG1_ZcdcMMTf9AIfrHP072fND47qHxMHvRI8JjHb_V93uI2Fx1YS0kj8NaLbDdeoTQBt1ydH4niVTikuYkK-lItbZ_iQ36d3kkGzEZfmMguVNyK0V8Kez4",
        "width": 1376,
        "height": 768
    },
    "refined_logo": {
        "url": "https://lh3.googleusercontent.com/aida/AEtjO1WJcFGP8RNPViifqaV4PwsdFnN_3agjuYLy6CEZu75WHuIWvWttv9mJpYJBHcw_hkF-8ygxHexWOFV5v3uvIikYvY-H7mJSixea54KeWO4ffB4i9WpN7T2UMMTed5pEuVmQDQH0gaJ0Gcu_BD-mrhEylkBKnB7Tns8nBrIUkkF-Z1vJ9jgO2GfduBsd3jltnNRVxAKgI8udvUSK2We4l4Xlygu8O7wT7DxV7U1pK6UZD3MJqJqqBUnIhH4",
        "width": 1024,
        "height": 1024
    },
    "app_icon": {
        "url": "https://lh3.googleusercontent.com/aida/AEtjO1XXPf-RnIfNVsdoDI2yyZwbcDRe_r5gHLr1rVs5ybC10RFsT6z9Ce9lnG-LZUjJo2SAj9-dt9LwnebDwwssRL6oMzkANvCZgmX2gw5140I79vU8oNFETvFy9bHQBhjq93-CuZ8TFSTk4ivMO3Q7F3w5r1tsxrUZdYGEfPc_4U4EV4zEV9luqBlVBDHul6F8PLuIDxWzajCj7c7l8zwQM61rRz83O3fCepFOpPPIekRNCJF3M7GWWRfvDyM",
        "width": 1024,
        "height": 1024
    },
    "apple_touch_icon": {
        "url": "https://lh3.googleusercontent.com/aida/AEtjO1Uv0mIX-dD09TLO0udt_7FTRhvou6IWF7kvQIA_cITHwFiPj1u-zzleXgh64uAPl8yX7IDdeKp4aTp8XikgJYx9XuwlnR_8QvlDWYiovyZviEtdKM9pp1MMIZ402hNkLsLvQ1-TizwvKECYC1oyb4IqHR0B9LzF1qma0o84ejYYi_fT8sYJ6QdY2HC7atEeAlh8F2qnh9sAoQU5h86QrRMc0qGIkXKLWWMkPJExE3Fcbn7eBRvmpvsrHQ",
        "width": 1024,
        "height": 1024
    }
}

def fetch_image(base_url, width):
    """Fetch full resolution image from Google CDN."""
    full_url = f"{base_url}=w{width}"
    req = urllib.request.Request(
        full_url,
        headers={"User-Agent": "Mozilla/5.0 (Playmaker Marketing Sync)"}
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = resp.read()
    return Image.open(io.BytesIO(data))

def main():
    os.makedirs(MARKETING_DIR, exist_ok=True)
    print(f"🔄 Syncing Stitch marketing assets to {ASSETS_DIR} ...")

    # 1. Wide Banner (16:9)
    print("  Downloading 16:9 Banner Ad...")
    banner_img = fetch_image(STITCH_ASSETS["banner_16_9"]["url"], STITCH_ASSETS["banner_16_9"]["width"])
    banner_path = os.path.join(MARKETING_DIR, "banner_ad_16_9.png")
    banner_img.save(banner_path, "PNG", optimize=True)
    print(f"  ✓ Saved {banner_path} ({os.path.getsize(banner_path):,} bytes)")

    # Standard WhatsApp / OpenGraph 1200x630
    print("  Optimizing social_share.png for WhatsApp / OpenGraph (1200x630)...")
    # Resize to 1200 width maintaining aspect ratio
    og_w = 1200
    og_h = 630
    # Center crop / resize
    w_orig, h_orig = banner_img.size
    aspect_target = og_w / og_h
    aspect_orig = w_orig / h_orig

    if aspect_orig > aspect_target:
        # Source is wider, scale by height then crop width
        new_h = og_h
        new_w = int(w_orig * (og_h / h_orig))
        resized = banner_img.resize((new_w, new_h), Image.Resampling.LANCZOS)
        left = (new_w - og_w) // 2
        og_img = resized.crop((left, 0, left + og_w, og_h))
    else:
        new_w = og_w
        new_h = int(h_orig * (og_w / w_orig))
        resized = banner_img.resize((new_w, new_h), Image.Resampling.LANCZOS)
        top = (new_h - og_h) // 2
        og_img = resized.crop((0, top, og_w, top + og_h))

    social_share_path = os.path.join(ASSETS_DIR, "social_share.png")
    # WhatsApp requires <300KB for quick link preview caching
    og_img.save(social_share_path, "PNG", optimize=True)
    size_kb = os.path.getsize(social_share_path) / 1024
    if size_kb > 300:
        # Fallback to high-quality JPEG if PNG is too large
        og_rgb = og_img.convert("RGB")
        og_rgb.save(social_share_path, "JPEG", quality=90, optimize=True)
        size_kb = os.path.getsize(social_share_path) / 1024
    print(f"  ✓ Saved {social_share_path} ({size_kb:.1f} KB)")

    # 2. 1:1 Social Media Card
    print("  Downloading 1:1 Social Media Card...")
    social_card_img = fetch_image(STITCH_ASSETS["social_card_1_1"]["url"], STITCH_ASSETS["social_card_1_1"]["width"])
    social_card_path = os.path.join(MARKETING_DIR, "social_card_1_1.png")
    social_card_img.save(social_card_path, "PNG", optimize=True)
    social_square_path = os.path.join(ASSETS_DIR, "social_share_square.png")
    social_card_img.save(social_square_path, "PNG", optimize=True)
    print(f"  ✓ Saved {social_card_path} and {social_square_path}")

    # 3. Email Header Banner
    print("  Downloading Email Header Banner...")
    email_banner_img = fetch_image(STITCH_ASSETS["email_header"]["url"], STITCH_ASSETS["email_header"]["width"])
    email_banner_path = os.path.join(MARKETING_DIR, "email_header_banner.png")
    email_banner_img.save(email_banner_path, "PNG", optimize=True)
    print(f"  ✓ Saved {email_banner_path}")

    # 4. Refined Playmaker Logo
    print("  Downloading Refined Playmaker Logo...")
    logo_img = fetch_image(STITCH_ASSETS["refined_logo"]["url"], STITCH_ASSETS["refined_logo"]["width"])
    logo_path = os.path.join(ASSETS_DIR, "logo.png")
    logo_img.save(logo_path, "PNG", optimize=True)
    playmaker_logo_path = os.path.join(ASSETS_DIR, "playmaker_logo.png")
    logo_img.save(playmaker_logo_path, "PNG", optimize=True)
    print(f"  ✓ Saved {logo_path} (1024x1024)")

    # 5. App Icon / Geometric Soccer Ball Favicon
    print("  Downloading App Icon & Generating Favicons...")
    app_icon_img = fetch_image(STITCH_ASSETS["app_icon"]["url"], STITCH_ASSETS["app_icon"]["width"])
    favicon_512 = app_icon_img.resize((512, 512), Image.Resampling.LANCZOS)
    favicon_path = os.path.join(ASSETS_DIR, "favicon.png")
    favicon_512.save(favicon_path, "PNG", optimize=True)

    favicon_192 = app_icon_img.resize((192, 192), Image.Resampling.LANCZOS)
    favicon_192.save(os.path.join(ASSETS_DIR, "favicon-192.png"), "PNG", optimize=True)

    favicon_32 = app_icon_img.resize((32, 32), Image.Resampling.LANCZOS)
    favicon_32.save(os.path.join(ASSETS_DIR, "favicon-32.png"), "PNG", optimize=True)

    # Multi-resolution favicon.ico
    ico_path = os.path.join(BASE_DIR, "favicon.ico")
    app_icon_img.save(ico_path, format="ICO", sizes=[(16, 16), (32, 32), (48, 48)])
    print(f"  ✓ Saved {favicon_path} and {ico_path}")

    # 6. Apple Touch Icon
    print("  Downloading Apple Touch Icon...")
    apple_icon_img = fetch_image(STITCH_ASSETS["apple_touch_icon"]["url"], STITCH_ASSETS["apple_touch_icon"]["width"])
    apple_icon_180 = apple_icon_img.resize((180, 180), Image.Resampling.LANCZOS)
    apple_path = os.path.join(ASSETS_DIR, "apple-touch-icon.png")
    apple_icon_180.save(apple_path, "PNG", optimize=True)
    print(f"  ✓ Saved {apple_path} (180x180)")

    print("🎉 All Stitch marketing and brand assets successfully synced and optimized!")

if __name__ == "__main__":
    main()
